{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fullnameOverride | default "default-secret" }}
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc }}
{{ end }}
{{ end }}
