fullnameOverride: my-nginx-secret
replicaCount: 2

secret:
  superSecretUrl: azeazeazeaze
  toto: titi

image:
  repository: nginx
  tag: "1.25.2"
  pullPolicy: IfNotPresent

defaultServiceType: ClusterIP
services:
  nginx:
    type: LoadBalancer
    port: 80
  loadbalancer:
    port: 3030

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "250m"
    memory: "64Mi"

nodeSelector: {}
tolerations: []
affinity: {}
